name: e_commerce_app_with_provider
description: "ShopWave - Modern E-Commerce App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.2.1
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true